// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ugrpc_pipe/ugrpc_pipe.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace UGrpc.Pipeline.GrpcPipe.V1 {
  public static partial class UGrpcPipe
  {
    static readonly string __ServiceName = "ugrpc_pipe.UGrpcPipe";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq> __Marshaller_ugrpc_pipe_CommandParserReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> __Marshaller_ugrpc_pipe_GenericResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest> __Marshaller_ugrpc_pipe_RenderRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply> __Marshaller_ugrpc_pipe_RenderBytesReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply> __Marshaller_ugrpc_pipe_RenderReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq> __Marshaller_ugrpc_pipe_PointCloudCaptureReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> __Marshaller_ugrpc_pipe_RegistrationResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq> __Marshaller_ugrpc_pipe_Converge3DRegistrationReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest> __Marshaller_ugrpc_pipe_HealthCheckRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.Status> __Marshaller_ugrpc_pipe_Status = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.Status.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq> __Marshaller_ugrpc_pipe_TrackingSensorClientReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp> __Marshaller_ugrpc_pipe_TrackingSensorTransformResp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> __Method_CommandParser = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CommandParser",
        __Marshaller_ugrpc_pipe_CommandParserReq,
        __Marshaller_ugrpc_pipe_GenericResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest, global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply> __Method_RenderImageBytes = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest, global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RenderImageBytes",
        __Marshaller_ugrpc_pipe_RenderRequest,
        __Marshaller_ugrpc_pipe_RenderBytesReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> __Method_RouteImageBytes = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RouteImageBytes",
        __Marshaller_ugrpc_pipe_RenderBytesReply,
        __Marshaller_ugrpc_pipe_GenericResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest, global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply> __Method_RenderImage = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest, global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RenderImage",
        __Marshaller_ugrpc_pipe_RenderRequest,
        __Marshaller_ugrpc_pipe_RenderReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> __Method_PointCloudCapture = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PointCloudCapture",
        __Marshaller_ugrpc_pipe_PointCloudCaptureReq,
        __Marshaller_ugrpc_pipe_RegistrationResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> __Method_Converge3DRegistration = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Converge3DRegistration",
        __Marshaller_ugrpc_pipe_Converge3DRegistrationReq,
        __Marshaller_ugrpc_pipe_RegistrationResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest, global::UGrpc.Pipeline.GrpcPipe.V1.Status> __Method_HealthCheck = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest, global::UGrpc.Pipeline.GrpcPipe.V1.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HealthCheck",
        __Marshaller_ugrpc_pipe_HealthCheckRequest,
        __Marshaller_ugrpc_pipe_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq, global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp> __Method_SubscribeTrackingSensorTransform = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq, global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeTrackingSensorTransform",
        __Marshaller_ugrpc_pipe_TrackingSensorClientReq,
        __Marshaller_ugrpc_pipe_TrackingSensorTransformResp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> __Method_UnsubscribeTrackingSensorTransform = new grpc::Method<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UnsubscribeTrackingSensorTransform",
        __Marshaller_ugrpc_pipe_TrackingSensorClientReq,
        __Marshaller_ugrpc_pipe_GenericResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::UGrpc.Pipeline.GrpcPipe.V1.UgrpcPipeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UGrpcPipe</summary>
    [grpc::BindServiceMethod(typeof(UGrpcPipe), "BindService")]
    public abstract partial class UGrpcPipeBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> CommandParser(global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply> RenderImageBytes(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> RouteImageBytes(global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply> RenderImage(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> PointCloudCapture(global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> Converge3DRegistration(global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.Status> HealthCheck(global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SubscribeTrackingSensorTransform(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::IServerStreamWriter<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> UnsubscribeTrackingSensorTransform(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UGrpcPipe</summary>
    public partial class UGrpcPipeClient : grpc::ClientBase<UGrpcPipeClient>
    {
      /// <summary>Creates a new client for UGrpcPipe</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public UGrpcPipeClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UGrpcPipe that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public UGrpcPipeClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected UGrpcPipeClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected UGrpcPipeClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp CommandParser(global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CommandParser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp CommandParser(global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CommandParser, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> CommandParserAsync(global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CommandParserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> CommandParserAsync(global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CommandParser, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply RenderImageBytes(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenderImageBytes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply RenderImageBytes(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RenderImageBytes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply> RenderImageBytesAsync(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenderImageBytesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply> RenderImageBytesAsync(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RenderImageBytes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp RouteImageBytes(global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RouteImageBytes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp RouteImageBytes(global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RouteImageBytes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> RouteImageBytesAsync(global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RouteImageBytesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> RouteImageBytesAsync(global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RouteImageBytes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply RenderImage(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenderImage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply RenderImage(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RenderImage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply> RenderImageAsync(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RenderImageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply> RenderImageAsync(global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RenderImage, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp PointCloudCapture(global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PointCloudCapture(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp PointCloudCapture(global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PointCloudCapture, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> PointCloudCaptureAsync(global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PointCloudCaptureAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> PointCloudCaptureAsync(global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PointCloudCapture, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp Converge3DRegistration(global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Converge3DRegistration(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp Converge3DRegistration(global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Converge3DRegistration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> Converge3DRegistrationAsync(global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Converge3DRegistrationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp> Converge3DRegistrationAsync(global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Converge3DRegistration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.Status HealthCheck(global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthCheck(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.Status HealthCheck(global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HealthCheck, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.Status> HealthCheckAsync(global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthCheckAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.Status> HealthCheckAsync(global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HealthCheck, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp> SubscribeTrackingSensorTransform(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeTrackingSensorTransform(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp> SubscribeTrackingSensorTransform(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeTrackingSensorTransform, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp UnsubscribeTrackingSensorTransform(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnsubscribeTrackingSensorTransform(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp UnsubscribeTrackingSensorTransform(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UnsubscribeTrackingSensorTransform, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> UnsubscribeTrackingSensorTransformAsync(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnsubscribeTrackingSensorTransformAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp> UnsubscribeTrackingSensorTransformAsync(global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UnsubscribeTrackingSensorTransform, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override UGrpcPipeClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UGrpcPipeClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(UGrpcPipeBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CommandParser, serviceImpl.CommandParser)
          .AddMethod(__Method_RenderImageBytes, serviceImpl.RenderImageBytes)
          .AddMethod(__Method_RouteImageBytes, serviceImpl.RouteImageBytes)
          .AddMethod(__Method_RenderImage, serviceImpl.RenderImage)
          .AddMethod(__Method_PointCloudCapture, serviceImpl.PointCloudCapture)
          .AddMethod(__Method_Converge3DRegistration, serviceImpl.Converge3DRegistration)
          .AddMethod(__Method_HealthCheck, serviceImpl.HealthCheck)
          .AddMethod(__Method_SubscribeTrackingSensorTransform, serviceImpl.SubscribeTrackingSensorTransform)
          .AddMethod(__Method_UnsubscribeTrackingSensorTransform, serviceImpl.UnsubscribeTrackingSensorTransform).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UGrpcPipeBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CommandParser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.CommandParserReq, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp>(serviceImpl.CommandParser));
      serviceBinder.AddMethod(__Method_RenderImageBytes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest, global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply>(serviceImpl.RenderImageBytes));
      serviceBinder.AddMethod(__Method_RouteImageBytes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.RenderBytesReply, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp>(serviceImpl.RouteImageBytes));
      serviceBinder.AddMethod(__Method_RenderImage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.RenderRequest, global::UGrpc.Pipeline.GrpcPipe.V1.RenderReply>(serviceImpl.RenderImage));
      serviceBinder.AddMethod(__Method_PointCloudCapture, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.PointCloudCaptureReq, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp>(serviceImpl.PointCloudCapture));
      serviceBinder.AddMethod(__Method_Converge3DRegistration, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.Converge3DRegistrationReq, global::UGrpc.Pipeline.GrpcPipe.V1.RegistrationResp>(serviceImpl.Converge3DRegistration));
      serviceBinder.AddMethod(__Method_HealthCheck, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.HealthCheckRequest, global::UGrpc.Pipeline.GrpcPipe.V1.Status>(serviceImpl.HealthCheck));
      serviceBinder.AddMethod(__Method_SubscribeTrackingSensorTransform, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq, global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorTransformResp>(serviceImpl.SubscribeTrackingSensorTransform));
      serviceBinder.AddMethod(__Method_UnsubscribeTrackingSensorTransform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UGrpc.Pipeline.GrpcPipe.V1.TrackingSensorClientReq, global::UGrpc.Pipeline.GrpcPipe.V1.GenericResp>(serviceImpl.UnsubscribeTrackingSensorTransform));
    }

  }
}
#endregion
