// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ugrpc_pipe/asset/ugrpc_render.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ugrpc_pipe/asset/ugrpc_render.proto</summary>
public static partial class UgrpcRenderReflection {

  #region Descriptor
  /// <summary>File descriptor for ugrpc_pipe/asset/ugrpc_render.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UgrpcRenderReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiN1Z3JwY19waXBlL2Fzc2V0L3VncnBjX3JlbmRlci5wcm90byKbAQoNUmVu",
          "ZGVyUmVxdWVzdBISCgpzY2VuZV9uYW1lGAEgASgJEh0KFWNhbWVyYV90cmFu",
          "c2Zvcm1hdGlvbhgCIAMoAhILCgNmb3YYAyABKAISEgoKcmVzb2x1dGlvbhgE",
          "IAMoBRIQCgh2ZGJfcGF0aBgFIAEoCRIQCghtb2RhbGl0eRgGIAEoCRISCgpj",
          "bGlwX3JhbmdlGAcgAygCIiEKC1JlbmRlclJlcGx5EhIKCmltYWdlX2RhdGEY",
          "ASABKAxiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RenderRequest), global::RenderRequest.Parser, new[]{ "SceneName", "CameraTransformation", "Fov", "Resolution", "VdbPath", "Modality", "ClipRange" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RenderReply), global::RenderReply.Parser, new[]{ "ImageData" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RenderRequest : pb::IMessage<RenderRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RenderRequest> _parser = new pb::MessageParser<RenderRequest>(() => new RenderRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RenderRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UgrpcRenderReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RenderRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RenderRequest(RenderRequest other) : this() {
    sceneName_ = other.sceneName_;
    cameraTransformation_ = other.cameraTransformation_.Clone();
    fov_ = other.fov_;
    resolution_ = other.resolution_.Clone();
    vdbPath_ = other.vdbPath_;
    modality_ = other.modality_;
    clipRange_ = other.clipRange_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RenderRequest Clone() {
    return new RenderRequest(this);
  }

  /// <summary>Field number for the "scene_name" field.</summary>
  public const int SceneNameFieldNumber = 1;
  private string sceneName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SceneName {
    get { return sceneName_; }
    set {
      sceneName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "camera_transformation" field.</summary>
  public const int CameraTransformationFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_cameraTransformation_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> cameraTransformation_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> CameraTransformation {
    get { return cameraTransformation_; }
  }

  /// <summary>Field number for the "fov" field.</summary>
  public const int FovFieldNumber = 3;
  private float fov_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Fov {
    get { return fov_; }
    set {
      fov_ = value;
    }
  }

  /// <summary>Field number for the "resolution" field.</summary>
  public const int ResolutionFieldNumber = 4;
  private static readonly pb::FieldCodec<int> _repeated_resolution_codec
      = pb::FieldCodec.ForInt32(34);
  private readonly pbc::RepeatedField<int> resolution_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> Resolution {
    get { return resolution_; }
  }

  /// <summary>Field number for the "vdb_path" field.</summary>
  public const int VdbPathFieldNumber = 5;
  private string vdbPath_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string VdbPath {
    get { return vdbPath_; }
    set {
      vdbPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "modality" field.</summary>
  public const int ModalityFieldNumber = 6;
  private string modality_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Modality {
    get { return modality_; }
    set {
      modality_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "clip_range" field.</summary>
  public const int ClipRangeFieldNumber = 7;
  private static readonly pb::FieldCodec<float> _repeated_clipRange_codec
      = pb::FieldCodec.ForFloat(58);
  private readonly pbc::RepeatedField<float> clipRange_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> ClipRange {
    get { return clipRange_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RenderRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RenderRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SceneName != other.SceneName) return false;
    if(!cameraTransformation_.Equals(other.cameraTransformation_)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Fov, other.Fov)) return false;
    if(!resolution_.Equals(other.resolution_)) return false;
    if (VdbPath != other.VdbPath) return false;
    if (Modality != other.Modality) return false;
    if(!clipRange_.Equals(other.clipRange_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SceneName.Length != 0) hash ^= SceneName.GetHashCode();
    hash ^= cameraTransformation_.GetHashCode();
    if (Fov != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Fov);
    hash ^= resolution_.GetHashCode();
    if (VdbPath.Length != 0) hash ^= VdbPath.GetHashCode();
    if (Modality.Length != 0) hash ^= Modality.GetHashCode();
    hash ^= clipRange_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SceneName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SceneName);
    }
    cameraTransformation_.WriteTo(output, _repeated_cameraTransformation_codec);
    if (Fov != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Fov);
    }
    resolution_.WriteTo(output, _repeated_resolution_codec);
    if (VdbPath.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(VdbPath);
    }
    if (Modality.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Modality);
    }
    clipRange_.WriteTo(output, _repeated_clipRange_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SceneName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SceneName);
    }
    cameraTransformation_.WriteTo(ref output, _repeated_cameraTransformation_codec);
    if (Fov != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Fov);
    }
    resolution_.WriteTo(ref output, _repeated_resolution_codec);
    if (VdbPath.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(VdbPath);
    }
    if (Modality.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Modality);
    }
    clipRange_.WriteTo(ref output, _repeated_clipRange_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SceneName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SceneName);
    }
    size += cameraTransformation_.CalculateSize(_repeated_cameraTransformation_codec);
    if (Fov != 0F) {
      size += 1 + 4;
    }
    size += resolution_.CalculateSize(_repeated_resolution_codec);
    if (VdbPath.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(VdbPath);
    }
    if (Modality.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Modality);
    }
    size += clipRange_.CalculateSize(_repeated_clipRange_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RenderRequest other) {
    if (other == null) {
      return;
    }
    if (other.SceneName.Length != 0) {
      SceneName = other.SceneName;
    }
    cameraTransformation_.Add(other.cameraTransformation_);
    if (other.Fov != 0F) {
      Fov = other.Fov;
    }
    resolution_.Add(other.resolution_);
    if (other.VdbPath.Length != 0) {
      VdbPath = other.VdbPath;
    }
    if (other.Modality.Length != 0) {
      Modality = other.Modality;
    }
    clipRange_.Add(other.clipRange_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          SceneName = input.ReadString();
          break;
        }
        case 18:
        case 21: {
          cameraTransformation_.AddEntriesFrom(input, _repeated_cameraTransformation_codec);
          break;
        }
        case 29: {
          Fov = input.ReadFloat();
          break;
        }
        case 34:
        case 32: {
          resolution_.AddEntriesFrom(input, _repeated_resolution_codec);
          break;
        }
        case 42: {
          VdbPath = input.ReadString();
          break;
        }
        case 50: {
          Modality = input.ReadString();
          break;
        }
        case 58:
        case 61: {
          clipRange_.AddEntriesFrom(input, _repeated_clipRange_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          SceneName = input.ReadString();
          break;
        }
        case 18:
        case 21: {
          cameraTransformation_.AddEntriesFrom(ref input, _repeated_cameraTransformation_codec);
          break;
        }
        case 29: {
          Fov = input.ReadFloat();
          break;
        }
        case 34:
        case 32: {
          resolution_.AddEntriesFrom(ref input, _repeated_resolution_codec);
          break;
        }
        case 42: {
          VdbPath = input.ReadString();
          break;
        }
        case 50: {
          Modality = input.ReadString();
          break;
        }
        case 58:
        case 61: {
          clipRange_.AddEntriesFrom(ref input, _repeated_clipRange_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class RenderReply : pb::IMessage<RenderReply>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RenderReply> _parser = new pb::MessageParser<RenderReply>(() => new RenderReply());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RenderReply> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UgrpcRenderReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RenderReply() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RenderReply(RenderReply other) : this() {
    imageData_ = other.imageData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RenderReply Clone() {
    return new RenderReply(this);
  }

  /// <summary>Field number for the "image_data" field.</summary>
  public const int ImageDataFieldNumber = 1;
  private pb::ByteString imageData_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString ImageData {
    get { return imageData_; }
    set {
      imageData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RenderReply);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RenderReply other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ImageData != other.ImageData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ImageData.Length != 0) hash ^= ImageData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ImageData.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ImageData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ImageData.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(ImageData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ImageData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(ImageData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RenderReply other) {
    if (other == null) {
      return;
    }
    if (other.ImageData.Length != 0) {
      ImageData = other.ImageData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ImageData = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ImageData = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
